### ISSUE TITLE
Native Screen Video Capture

### ISSUE THREAD

**Issue by JakeWharton** [mattprecious/telescope#14]
http://developer.android.com/about/versions/android-5.0.html#ScreenCapture

Two fingers triggers callback, dialog or something says "record video", two finger trigger again to stop. Bonus if you automatically clip the video to remove the two finger trigger from the end!

**Comment by yogurtearl** [comment]
:+1:

**Comment by mattprecious** [comment]
Since you've already tackled the hard parts of screen recording @JakeWharton, I think the difficult part here would be the UI and API. Should a view in a library be responsible for creating dialogs? Should it automatically stop recording when you leave the app? I think for some use cases it would be beneficial to keep recording once the activity is paused (recording bugs when intenting out to different apps), but that also means you need to return to your app to stop the recording.

I'm inclined to say that Telecine is the better solution for video capturing. Can Telecine expose an API that Telescope can call to trigger the overlay? Two fingers to capture a screenshot, three fingers to start Telecine with pre-defined configurations and a callback to handle the video.

**Comment by JakeWharton** [comment]
https://github.com/JakeWharton/Telecine/issues/4

**Comment by NightlyNexus** [comment]
What pre-defined configurations would be best for Telecine to accept, and what information should come back in the callback?

**Comment by mattprecious** [comment]
I think the only thing that I would need in the callback is a `File` or a `Uri` and possibly a result status (if the presence of the file is not enough of an indicator).

As for configurations... video size would be a nice one. Not sure what else would be useful. Maybe a destination file?

**Comment by mattprecious** [comment]
Telecine isn't adding the API and I have no interest in adding or maintaining video code so I'm going to close this one.
