### ISSUE TITLE
Capturing dialogs

### ISSUE THREAD

**Issue by amatkivskiy** [mattprecious/telescope#44]
Hi guys,
Thanks for a great tool 👍 

What about capturing dialogs? Are there any plans for supporting this?

**Comment by mattprecious** [comment]
Dialogs are in a separate window so there isn't really anything that I can do. If you make your own dialog class, you can configure it so that it conditionally wraps its content in a `TelescopeLayout` on your debug builds. If you're running on 21+ it'll take a full system screenshot. Otherwise, it'll take a snapshot of the dialog.

**Comment by amatkivskiy** [comment]
@mattprecious Thanks for explanation. I can close the issue.
